"""agent decisions and operator feedback

Revision ID: d3893a762054
Revises: b1a2c3d4e5f6
Create Date: 2026-09-03 16:16:43.139259
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d3893a762054"
down_revision: str | None = "b1a2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_OWNED_TABLES = ("agent_decisions", "operator_feedback")


def _enable_rls() -> None:
    """Row-level security for the new tables, matching b1a2c3d4e5f6.

    Both carry owner_id, so the same policy shape applies. FORCE so the table owner is
    not exempt. PostgreSQL only; SQLite has no RLS and the migration no-ops there.
    """
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in _OWNED_TABLES:
        op.execute(sa.text(f"ALTER TABLE {table} ENABLE ROW LEVEL SECURITY"))
        op.execute(sa.text(f"ALTER TABLE {table} FORCE ROW LEVEL SECURITY"))
        op.execute(
            sa.text(
                f"""
                CREATE POLICY {table}_owner_isolation ON {table}
                USING (owner_id = current_setting('tayr.current_user_id', true))
                WITH CHECK (owner_id = current_setting('tayr.current_user_id', true))
                """
            )
        )


def _disable_rls() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for table in _OWNED_TABLES:
        op.execute(sa.text(f"DROP POLICY IF EXISTS {table}_owner_isolation ON {table}"))
        op.execute(sa.text(f"ALTER TABLE {table} DISABLE ROW LEVEL SECURITY"))


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_decisions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("job_id", sa.String(length=36), nullable=False),
        sa.Column("track_id", sa.String(length=36), nullable=False),
        sa.Column("site_id", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("attention", sa.String(length=16), nullable=False),
        sa.Column("uncertainty", sa.String(length=32), nullable=False),
        sa.Column("rule_id", sa.String(length=64), nullable=False),
        sa.Column("record_json", sa.Text(), nullable=False),
        sa.Column("audit_hash", sa.String(length=64), nullable=False),
        sa.Column("prose_diverged", sa.Boolean(), nullable=False),
        sa.Column("synthetic", sa.Boolean(), nullable=False),
        sa.Column("model", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("rounds_used", sa.Integer(), nullable=False),
        sa.Column("round_cap_reached", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("notification_ref", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["track_id"], ["tracks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("track_id", name="uq_agent_decisions_track"),
    )
    op.create_index(op.f("ix_agent_decisions_job_id"), "agent_decisions", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_agent_decisions_owner_id"), "agent_decisions", ["owner_id"], unique=False
    )
    op.create_index(
        "ix_agent_decisions_site_created",
        "agent_decisions",
        ["site_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_decisions_site_id"), "agent_decisions", ["site_id"], unique=False
    )
    op.create_index(
        op.f("ix_agent_decisions_track_id"), "agent_decisions", ["track_id"], unique=False
    )
    op.create_table(
        "operator_feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("decision_id", sa.String(length=36), nullable=False),
        sa.Column("owner_id", sa.String(length=36), nullable=False),
        sa.Column("response", sa.String(length=32), nullable=False),
        sa.Column("responder", sa.String(length=128), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["decision_id"], ["agent_decisions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operator_feedback_decision_id"), "operator_feedback", ["decision_id"], unique=False
    )
    op.create_index(
        op.f("ix_operator_feedback_owner_id"), "operator_feedback", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###

    _enable_rls()


def downgrade() -> None:
    _disable_rls()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_operator_feedback_owner_id"), table_name="operator_feedback")
    op.drop_index(op.f("ix_operator_feedback_decision_id"), table_name="operator_feedback")
    op.drop_table("operator_feedback")
    op.drop_index(op.f("ix_agent_decisions_track_id"), table_name="agent_decisions")
    op.drop_index(op.f("ix_agent_decisions_site_id"), table_name="agent_decisions")
    op.drop_index("ix_agent_decisions_site_created", table_name="agent_decisions")
    op.drop_index(op.f("ix_agent_decisions_owner_id"), table_name="agent_decisions")
    op.drop_index(op.f("ix_agent_decisions_job_id"), table_name="agent_decisions")
    op.drop_table("agent_decisions")
    # ### end Alembic commands ###
